# Generated by Django 4.2.29 on 2026-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='advance_reminder_days',
            field=models.PositiveIntegerField(
                default=14,
                help_text='Send one reminder when this many days remain.',
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_reminder_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='repeat_reminder_morning',
            field=models.BooleanField(
                default=True,
                help_text='Send morning reminders inside the repeated reminder window.',
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='repeat_reminder_night',
            field=models.BooleanField(
                default=True,
                help_text='Send night reminders inside the repeated reminder window.',
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='repeat_reminder_start_days',
            field=models.PositiveIntegerField(
                default=7,
                help_text='Start morning and night reminders when this many days remain.',
            ),
        ),
    ]
