# Generated by Django 4.2.29 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_reminder_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField()),
                ('slot', models.CharField(max_length=10)),
                ('days_until', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=120)),
                ('reminder_key', models.CharField(max_length=120)),
                ('subscription', models.ForeignKey(on_delete=models.CASCADE, related_name='notification_history', to='subscriptions.subscription')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
